name: Docker Workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Attempt to pull previous Docker image for caching
        run: docker pull matttennison:/bus-lights:$(git rev-parse --short HEAD^1) || true

      - name: Build Image
        run: docker build . -t matttennison/bus-lights:$(git rev-parse --short HEAD)

      - name: Log in to Docker
        env: 
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u matttennison -p $(echo $DOCKER_TOKEN)

      - name: Push Image
        run: docker push matttennison/bus-lights:$(git rev-parse --short HEAD)