name: Docker Workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: List folder contents
        run: ls
      - name: Build Image
        run: docker build . -t bus-lights:latest