name: Docker
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Attempt to pull previous Docker images for caching
        run: |
          docker pull matttennison/bus-lights:$GITHUB_SHA
          docker pull matttennison/bus-lights:$GITHUB_SHA-stage
        continue-on-error: true

      - name: Build stage image
        run: docker build . -t matttennison/bus-lights:$GITHUB_SHA-stage --target=stage

      - name: Run unit tests
        run:  docker run matttennison/bus-lights:$GITHUB_SHA-stage yarn test src/

      - name: Build final image
        run: docker build . -t matttennison/bus-lights:$GITHUB_SHA

      - name: Log in to Docker
        env: 
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u matttennison -p $DOCKER_TOKEN

      - name: Push Images
        run: |
          docker push matttennison/bus-lights:$GITHUB_SHA-stage
          docker push matttennison/bus-lights:$GITHUB_SHA
      
      - name: Push final image as latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag matttennison/bus-lights:$GITHUB_SHA matttennison/bus-lights:latest
          docker push matttennison/bus-lights:latest
  