name: Docker Workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Image
        run: docker build . -t matttennison/bus-lights:$(git rev-parse --short HEAD)
  push:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Push Image
        run: docker push matttennison/bus-lights:$(git rev-parse --short HEAD)