name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with: 
          node-version: '10.16.3'

      - uses: Borales/actions-yarn@master
        args: "install" 

      - uses: Borales/actions-yarn@master
        args: "test" 